### ISSUE TITLE
Opera GX

### ISSUE THREAD

**Issue by Kingtoxix** [ShrimpCryptid/SplatNet-Alerts#9]
Hi! I use opera GX and the notifactions arent working even tho i have them on 
![afbeelding_2024-05-09_150709707](https://github.com/ShrimpCryptid/SplatNet-Alerts/assets/121696370/7176a34e-ce0c-4ce6-8cc5-3c2507ed00e9)

**Comment by Kingtoxix** [comment]
fixed it

**Comment by ShrimpCryptid** [comment]
Oh, glad this got resolved! What specific steps did you take to fix the issue? I might make a writeup in the pinned guide.
